---
title: Haruspex
email: sales@haruspex.dev
description: >
  Gain insights into your tests
  Haruspex provide you information at both the low and the high level immediately
  See what is failing and why, track performance regression, find flaky tests history
  Get Observability into your test suite today
tagline: "Gain insights into your tests"
logo: "/images/haruspex-square-logo.png"
baseurl: ""
url: "https://haruspex.dev"
social:
  name: Haruspex
  links:
    - https://twitter.com/HaruspexDev
seo:
  type: "Organization"
twitter:
  username: HaruspexDev
  card: summary
permalink: "/:title/"
palette: blue
header:
  title: Haruspex
  logo_img: "/images/haruspex-full-logo-responsive.svg"
  has_nav: true
  nav_links:
  - label: Home
    url: "/"
  - label: Pricing
    url: "/pricing"
  - label: About Us
    url: "/about"
  - label: Login
    url: https://ui.haruspex.dev
    primary: true
    new_window: true
  - label: Sign Up
    url: https://ui.haruspex.dev/auth/auth0/new?screen_hint=signup
    primary: true
footer:
  logo_img: "/images/haruspex-full-logo-dark-background-responsive.svg"
  has_nav: true
  nav_title: Company
  nav_links:
  - label: About Us
    url: "/about"
  - label: Sign Up
    url: https://ui.haruspex.dev/auth/auth0/new?screen_hint=signup
  - label: Privacy Policy
    url: "/privacy"
  - label: Contact
    url: mailto:sales@haruspex.dev
  has_social: true
  social_title: Community
  social_links:
  - label: Twitter
    url: https://twitter.com/HaruspexDev
    new_window: true
  has_subscribe: false
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Liveware Problems. All rights reserved."
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
- jekyll-sitemap
- jekyll-seo-tag

exclude:
- LICENSE.md
- README.md
- netlify.toml
collections:
  posts:
    permalink: "/posts/:title/"
    output: true
