---
title: Haruspex
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Haruspex
  logo_img: "/images/haruspex-full-logo-responsive.svg"
  has_nav: true
  nav_links:
  - label: Home
    url: "/"
  - label: Pricing
    url: "/pricing"
  - label: About Us
    url: "/about"
  - label: Login
    url: https://ui.haruspex.dev
    primary: true
    new_window: true
  - label: Sign Up
    url: https://ui.haruspex.dev?screen_hint=signup
    primary: true
footer:
  logo_img: "/images/haruspex-full-logo-dark-background-responsive.svg"
  has_nav: true
  nav_title: Company
  nav_links:
  - label: About Us
    url: "/about"
  - label: Sign Up
    url: https://ui.haruspex.dev?screen_hint=signup
  - label: Contact
    url: mailto:sales@haruspex.dev
  has_social: true
  social_title: Community
  social_links:
  - label: Twitter
    url: https://twitter.com/HaruspexDev
    new_window: true
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Liveware Problems. All rights reserved."
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
